server:
  port: 2101
  max-http-header-size: 10000000
  tomcat:
    max-http-post-size: -1
mybatis-plus:
  mapper-locations:
  - classpath:mapper/*.xml
  - classpath:mapper/*/*.xml
  - classpath*:mapper/*/*/*.xml
  type-aliases-package: com.eurekaproducer.*.entity
spring:
  datasource:
    sql-script-encoding: UTF-8
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-j6c5ybh2z55369e5t0o.mysql.rds.aliyuncs.com:3306/gaia_mall_test?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&autoReconnect=true
    username: gaia_mall_test
    password: gaia_mall_test
  thymeleaf:
    mode: LEGACYHTML5
    encoding: UTF-8
    cache: false
    servlet:
      content-type: text/html
    prefix: classpath:/templates/
  messages:
    basename: i18n/messages
  redis:
    password:
    database: 0
    port: 6379
    host: 127.0.0.1
    lettuce:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1ms
    timeout: 10000
  servlet:
    multipart:
      max-file-size: 10MB

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1001/eureka/
